Changeset created on Thu Jan  6 14:42:02 CET 2011 by Seek You Too

Description: IOError in socket.connect now handled 

    Socket.connect can raise an IOError with message "No route to host". This removes the oaiharvester from the reactor. This is now logged and retried like a SocketError

Baseline version: https://meresco.svn.sourceforge.net/svnroot/meresco/meresco-oai/workingsets/3.4-Edurep/version_0

diff --unidirectional-new-file --exclude='*.so' --exclude='*.o' --exclude=.svn --exclude='*.pyc' --exclude=deps.d --exclude=applied --recursive --unified version_0/meresco/oai/oaiharvester.py version_1/meresco/oai/oaiharvester.py
--- version_0/meresco/oai/oaiharvester.py	2010-12-06 12:05:10.000000000 +0100
+++ version_1/meresco/oai/oaiharvester.py	2011-01-06 14:41:04.000000000 +0100
@@ -161,6 +161,9 @@
                 if errno != EINPROGRESS:
                     yield self._retryAfterError("%s: %s" % (errno, msg))
                     continue
+            except IOError, e:
+                yield self._retryAfterError(str(e))
+                continue
             self._reactor.addWriter(sok, self._loop.next)
             yield
             self._reactor.removeWriter(sok)
diff --unidirectional-new-file --exclude='*.so' --exclude='*.o' --exclude=.svn --exclude='*.pyc' --exclude=deps.d --exclude=applied --recursive --unified version_0/test/oaiharvestertest.py version_1/test/oaiharvestertest.py
--- version_0/test/oaiharvestertest.py	2010-12-06 12:05:10.000000000 +0100
+++ version_1/test/oaiharvestertest.py	2011-01-06 14:41:04.000000000 +0100
@@ -134,6 +134,20 @@
         noAddressAssociatedWithHost = "-5: No address associated with hostname\n" == self._err.getvalue()
         self.assertTrue(nameOrServiceNotKnown or noAddressAssociatedWithHost, self._err.getvalue())
 
+    def testIOErrorInSocketConnect(self):
+        import meresco.oai.oaiharvester
+        old_socket = meresco.oai.oaiharvester.socket
+        try:
+            mockSock = CallTrace("socket")
+            mockSock.exceptions['connect'] = IOError("IOError: 113")
+            meresco.oai.oaiharvester.socket = lambda: mockSock
+            harvester, observer, reactor = self.getHarvester("UEYR^$*FD(#>NDJ.khfd9.(*njnd.nl", 88, "/oai", 'dc')
+            callback = reactor.calledMethods[0].args[1]
+            callback() # connect
+            self.assertEquals("IOError: 113\n", self._err.getvalue())
+        finally:
+            meresco.oai.oaiharvester.socket = old_socket
+
     def testInvalidHostConnectionRefused(self):
         harvester, observer, reactor = self.getHarvester("127.0.0.255", 9876, "/oai", 'dc')
         callback = reactor.calledMethods[0].args[1]
